site_name: 'backstage-sample-techdocs'

plugins:
  - techdocs-core

docs_dir: ./

nav:
  - Home: README.md
  - Lib 1:
      - Lib 1: 'lib1/README.md'
  - Lib 2: 'lib2/README.md'
  - Lib 3: 'lib3/README.md'
